"""``docspine._core`` —— Rust 扩展模块的类型存根(PEP 561)。

块 / 表格 / OCR 结果以 ``dict[str, Any]`` 返回(可自省);键见 README。
"""

from __future__ import annotations

from os import PathLike
from typing import Any

__version__: str

class DocError(Exception):
    """docspine 异常层级的根。"""

class DocZipError(DocError): ...
class DocXmlError(DocError): ...
class DocUnsupportedError(DocError): ...
class DocOcrError(DocError): ...

class Document:
    """一份已解析的 Word 文档句柄。"""

    @property
    def block_count(self) -> int: ...
    def body(self) -> list[dict[str, Any]]: ...
    def paragraphs(self) -> list[dict[str, Any]]: ...
    def tables(self) -> list[dict[str, Any]]: ...
    def text(self) -> str: ...
    def __len__(self) -> int: ...

def version() -> str: ...
def open(path: str | PathLike[str]) -> Document: ...
def open_bytes(data: bytes) -> Document: ...
def probe_doc(data: bytes) -> dict[str, Any]: ...

# 仅在以 `--features ocr` 构建时存在。
def ocr_image(data: bytes) -> list[dict[str, Any]]: ...
def reconstruct_image_table(data: bytes) -> list[dict[str, Any]]: ...
